type: app
description: Default stackfile usecase description
# template used to create the project
template: incredible-vagrant-startup-kit-startup-kit/<template-name>
inputs:
  some_input: value
# list of plugins to be applied after project creation
plugins:
  - plugin: incredible-vagrant-startup-kit-startup-kit/<plugin-name>
    inputs:
      some_input: value
      some_list:
        - item1
        - item2
