name: generate-and-apply-k8s-manifests
description: Convert docker compose file to kubernetes manifests and run them
supported-os:
- windows
- linux
- mac
requirements-check:
  dependency-example:
    check-command: vagrant version
    info: vagrant is not installed
command: 
  linux: |
    vagrant ssh -c 'kompose convert -f project/docker-compose.yaml -o project/manifests.yaml'
    vagrant ssh -c 'sudo kubectl apply -f project/manifests.yaml'
